### ISSUE TITLE
What's the benefit of `copy_op` when generating gradient graph?

### ISSUE THREAD

**Issue by formath** [dmlc/nnvm#144]
@ptrendx 
I don't get the point about what's the  benefit of `copy_op` in `gradient.cc`.   Why not just use `ret.outputs[counter] = entry.sum`? Thanks. 
```
    if (copy_op != nullptr) {
      auto kv = unique_grads.find(entry.sum);
      if (kv == unique_grads.end()) {
        unique_grads.emplace(std::move(entry.sum), std::make_pair(1, counter));
      } else {
        NodePtr copy_node = Node::Create();
        std::ostringstream os;
        os << entry.sum.node->attrs.name << "_" << kv->second.first << "_copy";
        kv->second.first++;
        copy_node->attrs.op = copy_op;
        copy_node->attrs.name = os.str();
        copy_node->inputs.emplace_back(entry.sum);
        if (copy_node->attrs.op->attr_parser != nullptr) {
            copy_node->attrs.op->attr_parser(&(copy_node->attrs));
        }
        unique_grads.emplace(NodeEntry{std::move(copy_node), 0, 0}, std::make_pair(1, counter));
      }
    } else {
        ret.outputs[counter] = entry.sum;
    }
```
https://github.com/dmlc/nnvm/blob/e842c098decf9f5eb6bd84e307c58e50078596b7/src/pass/gradient.cc#L208

**Comment by jermainewang** [comment]
According to the code, this is for situation where `grad_xs` contains duplicate NodeEntry so their gradient entries are also the same. It tries to make those gradient entries distinct by doing copy. Don't know the real application for this though.

**Comment by formath** [comment]
@jermainewang Can you give me an example in practice?

**Comment by ptrendx** [comment]
Let's say you have a very simple graph that just adds 2 tensors: c =a+b. Normally when you see such addition you would want to omit copying (the gradient to a and b is the same so why make 2 tensors with the same information). But if this addition is on the edge of the graph as in this example, you may bind 2 actual tensors to those 2 output gradients. This fails because those 2 gradients are actually the same thing. That is why this code looks at the outputs of the graph and when it sees duplicates it makes them unique by applying copy. Does that make sense?

**Comment by formath** [comment]
Got it. Thanks @ptrendx
