### ISSUE TITLE
Performance on M40

### ISSUE THREAD

**Issue by minminsun** [dmlc/nnvm#230]
In the NNVM Compiler announcement (http://www.tvmlang.org/2017/10/06/nnvm-compiler-announcement.html), the performance comparisons between NNVM Compiler and MXNet+cuDNN on GPU are very impressive. But I have a little confusion with the claim -- "These improvements are due to the joint graph level and kernel level optimizations".

To confirm the kernel level optimization, I compared the performance of all the conv2D layers in the ResNet18 with TVM generated kernel against cuDNN on M40 GPU. But according to the results bellow, the kernels TVM generated don't seem to make the conv2D layers faster than cuDNN.
![image](https://user-images.githubusercontent.com/17308199/32714503-25fa30b0-c889-11e7-84ba-3190db6a39f6.png)
So my question is whether the performance improvements of NNVM Compiler on ResNet18 are really due to the joint graph level and kernel level optimizations or only the graph level optimization so far? Thank you!

**Comment by tqchen** [comment]
Related issue in https://github.com/dmlc/nnvm/issues/206 

All the code in the end to end benchmark is generated by TVM.

In terms of conv kernels in resnet we are faster on some and slower on others. The gap between the two should have been smaller though. This difference could due to either the schedule was tuned under K80 and might need some adaptation,  or something missing in the benchmark script(we need to turn on nnvm compiler hook and set proper unroll factors). You can checkout out the end to end benchmark script.

In total under k80 we are a bit slower without graph optimization, and faster with graph optimization on. The optimization is join in a sense that graph optimizer relies on TVM's auto generated kernel to perform optimization such as fusing and cannot rely on cudnn to do that. We can expect more improvements.

cc @Huyuwei @Laurawly

**Comment by minminsun** [comment]
Thanks a lot for your quick and informative reply. @tqchen 
 >> or something missing in the benchmark script(we need to turn on nnvm compiler hook and set proper unroll factors). You can checkout out the end to end benchmark script.
The benchmark script I was running is https://github.com/dmlc/nnvm/blob/master/tutorials/imagenet_inference_gpu.py. Is this the end to end benchmark script you mentioned? I don't see the settings there.

**Comment by Huyuwei** [comment]
@minminsun  Better use this script https://github.com/dmlc/nnvm/blob/master/examples/benchmark/gpu_imagenet_bench.py#L56

You can set opt_level and unroll factor.
