### ISSUE TITLE
[Operator] Support LRN

### ISSUE THREAD

**Issue by renjiangyong** [dmlc/nnvm#337]
when I running the vgg model on nnvm, I got an error "Operator: LRN is not supported in nnvm", maybe the LRN is not implement, Did we have a plan to support LRN layer in nnvm, pls tell me the schedule when have a plan. thank you very much!

jiangyong

**Comment by chenqy4933** [comment]
Maybe you can copy the LRN layer from the src/operator of mxnet , today I run mxnet's amalgamation in android with the same problem ,finally I solve it by add the LRN code into amalgamation manually.

**Comment by kaishijeng** [comment]
@chenqy4933 
Can you provide detailed instructions of how you do this?

It is a big issue to use NNVM/TVM because a lot of popular models can not be evaluated due to missing operators in various Frontends (like mxnet/keras). If NNVM can import all operators from MXNET/Keras frameworks directly, it will make life easier to use NNVM/TVM

Thanks,

**Comment by renjiangyong** [comment]
@chenqy4933 if NNVM can import operators from MXNET frameworks directly, pls tell me how to do this, thank you . it is helpful to me

**Comment by chenqy4933** [comment]
I just import the operator from mxnet to the amalgamation ,because amalgamation is a part of mxnet ,I copy the code directly to the amalgamation . I have not try to import operators to nnvm ,maybe It is a solution to import it from mxnet . sorry!!!!

**Comment by tqchen** [comment]
LRN is supported by https://github.com/dmlc/tvm/pull/1051 by @PariksheetPinjari909  Now only changes in nnvm is needed

**Comment by tqchen** [comment]
move to https://github.com/dmlc/tvm/issues/1185
