### ISSUE TITLE
[question] What is the relation between Tensor and NodeEntry?

### ISSUE THREAD

**Issue by nhynes** [dmlc/nnvm#406]
Specifically, can [NodeEntries](https://github.com/dmlc/nnvm/blob/33c0812519ab2607c2ccf8242be773acf5d68a36/include/nnvm/node.h#L31) be returned from [FTVMCompute](https://github.com/dmlc/nnvm/blob/d93d0c6330f94604d52e25caef818d71f429cb5b/include/nnvm/compiler/op_attr_types.h#L58) instead of [Tensors](https://github.com/dmlc/tvm/blob/52871592db15b0354e706724ee110338fc1bb7bc/include/tvm/tensor.h#L32) (as in [FGradient](https://github.com/dmlc/nnvm/blob/d93d0c6330f94604d52e25caef818d71f429cb5b/include/nnvm/op_attr_types.h#L163))? It looks like this is possible since both are Nodes, but the conversion between NodeRef and NodePtr isn't obvious.

**Comment by tqchen** [comment]
This is mainly due to the current way NNVM is organized. Currently the high level computational graph in NNVM is independent  from low level TVM dataflow. So they are essentially two different things. Some of this is due to legacy issue that NNVM is designed before TVM.

We are working toward moving more of NNVM's node system to TVM's node system. In the meanwhile, it is still helpful to distinguish between low level tensor operator dataflow and computational graph version. So NodeEntries are computational graph representation  and all graph transformation manipulates NodeEntries instead of Tensors.

The compilation to TVM(FTVMCompute) returns tvm Tensors

**Comment by nhynes** [comment]
Interesting. That implies that creating an FGradient which performs both pre-existing and specialized computation would require building the graph of reused components (e.g. sum) and then making an FTVMCompute for the specific parts (instead of the monolithic CreateGradNode->FTVMCompute). Ideally, the amount (and size) of new FTVMComputes would be minimized to facilitate higher-order autograd.

Thanks for the answer!
