### ISSUE TITLE
op not found if MXListAllOpNames not called first

### ISSUE THREAD

**Issue by pluskid** [dmlc/nnvm#51]
It seems calling `NNGetOpHandle` (say with `"_copyto"`) will fail with op not found if `MXListAllOpNames` is not called first.

Julia has a compiling phase, where `MXListAllOpNames` will be called to compile functions. A fresh run of julia will not call `MXListAllOpNames` but will call `NNGetOpHandle` to locate the registered ops. Adding an extra dummy call to `MXListAllOpNames` to the beginning of the program will prevent crashing.

Ref dmlc/MXNet.jl#145

**Comment by tqchen** [comment]
Was due to legacy issue of registration phase that calls legacy registration. 
https://github.com/dmlc/mxnet/blob/nnvm/src/c_api/c_api_symbolic.cc#L45

This was not problem of NNVM but legacy issue in mxnet, we can add a MXGetOpHandle instead which calls the legacy registration function and use MXGetOpHandle instead.
