### ISSUE TITLE
Shape Inference with Hints for Gradient Ops

### ISSUE THREAD

**Issue by tqchen** [dmlc/nnvm#73]
Currently the shape/type inference for gradient op requires the registry of FBackwardInGradIndex and FBackwardOutToInIndex. Both are a bit cumbersome to do so.

Here is a second way to solve this problem
## In NNVM
- Add an operator in host language identity_attr_as_rhs(data, rhs), where the output is identity as data, but the type is constrained to be same as rhs
- In gradient pass, optionally enable pass a function AttrConstraintHint(input, rhs), which the source package will return identity_attr_as_rhs. This hint is inserted for every output of gradient ops, if FInferShape is not defined for that op.
  - This will not be inserted if FInfershape is already defined.
- Enable an attribute FIgnoreInputs  to the op do not have dataflow dependency on the data, but simply takes the information as hint  
  - Related ops include ones_like, and zeros_like
  -  Change memory allocation to take this into account and not retain memory for those index that are ignored.
## In Host Package(TinyFlow/ MXNet)
-  In host package, register identity_attr_as_rhs as identity compute, note that it will turn into a NOP if inplace happens.
- Update the https://github.com/dmlc/mxnet/blob/nnvm/src/executor/inplace_addto_detect_pass.cc to allow backprop replacement of addto to pass through identity maps

**Comment by tqchen** [comment]
related to #70 https://github.com/dmlc/nnvm/issues/52

**Comment by tqchen** [comment]
@piiswrong @jermainewang

**Comment by jermainewang** [comment]
I think another way to do this is having a simple macro system. As we've discussed, the problem of maintaining attributes in graph is that the `Symbol` object does not contain attributes. So when user have following codes:
```python
z = x + y
dx = tf.grad(z, [x])   # Need to apply NNVM's Gradient pass here
ret = tf.exp(dx) * 2 - 3
```
, the gradient information cannot be carried on by the symbol composition. I think the main problem is that we are mixing the front-end construction and graph passes here. Remember, in a compiler stages, there is **no** looking back (e.g. once you finish syntax parsing, you go to semantic parsing and you could not go back). The problem here is that we want to have NNVM processing (similar to semantic parsing) in the middle of syntax parsing, which is object to the principal of compiler stages.

If the `tf.grad` is just a *macro* node that will be expanded in NNVM's passes, then all the information could be kept. So the above code will correspond to following graph:
```
[x, y] -> op(+) -> z
[x, z] -> macro_op(grad) -> dx
dx -> op(exp) -> op(*2) -> op(-3) -> ret
```
The *macro* here is like a temporary container that saves the front-end information for later NNVM's pass processing. In this way, there is *no* involvement of NNVM during symbol construction. I believe this will solve the problem in a more elegant way.

**Comment by tqchen** [comment]
This seems increase the complexity of design a lot. I think we will go with the solution in here for now. While being able to upgrade later

**Comment by tqchen** [comment]
seems the backward index is needed actually for current case.

The reason was the following corner case

- assume we have two output from backward_mul, and we only need the gradient of the first input.
 - Although the idenity_with_attr_like will be inserted into the second gradient, it is dropped because the gradient is no longer needed.

So infer shape function won't be able to infer the shape of that output, although in practice that output is also not needed(req=kNullOp). To really support this way, we need every op to support kNullOp correctly and infer shape need to ignore those results that are not needed.

I feel this creates a bit complexity, and seems the old way of FBackwardInGradIndex  and FBackwardOutToInIndex is still the easiest solution to this problem.

**Comment by jermainewang** [comment]
What's wrong if the gradient of the second input is not needed at all?

**Comment by jermainewang** [comment]
Another possible solution: could we dynamically add a FInferShape for the backward op during gradient pass? To support this, we should allow FInferShape to be NodeAttr rather than OpAttr.

**Comment by tqchen** [comment]
@jermainewang Mainly due to the limitation of current shape inference and executor. because both gradients are outputed via the same operator, the shape is needed

**Comment by tqchen** [comment]
This is formally solved by https://github.com/dmlc/nnvm/pull/85
